init(task19) upload task19
Dimakov9/react-homeworks pull request #10
Opened 2022-04-30 12:44 UTC by Dimakov9

2022-05-02 13:40 UTC, PaulVersAtile requested changes

2022-05-02 13:40 UTC, PaulVersAtile commented on src/UserList.jsx
> +  let res = data.map(function (item) {
const

2022-05-06 15:14 UTC, Dimakov9 commented on src/UserList.jsx
> +  let res = data.map(function (item) {
пофиксил

2022-05-10 14:03 UTC, PaulVersAtile approved these changes

2022-05-15 11:54 UTC, merged